site_name: NotAlone Documentation
site_description: User and Developer Documentation for NotAlone App
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user/getting_started.md
    - Member Management: user/member_management.md
  - Administrator Guide:
    - Getting Started: admin/getting_started.md
    - PayPal Setup: admin/paypal_setup.md
    - Discourse Setup: admin/discourse_setup.md
    - Mailjet Setup: admin/mailjet_setup.md
    - Tenant Setup: admin/tenant_setup.md
  - Developer Guide:
    - General Instructions: developer/general_instructions.md
    - CSS Roles: developer/css_roles.md
    - Payments: developer/payments.md
    - Routing: developer/routing.md
    - Schema: developer/schema.md
    - Skeleton Loading: developer/skeleton_loading.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

repo_url: https://github.com/yahiakala/notalone-app
edit_uri: edit/master/docs
